-- Builds ForeverArtisan_Contacts/SeedTrainers.lua from a ForeverArtisan_Contacts.lua SavedVariables
-- file: the profession trainers Kerry's characters met on the Forever beta.
--   lua5.1 tools/build_seed.lua <path to ForeverArtisan_Contacts.lua> > ForeverArtisan_Contacts/SeedTrainers.lua
-- Keeps only what a player needs (who, where, what they teach). Drops seenBy (a character name),
-- builds, reactions and timestamps finer than the day. Never edit the output by hand; rerun this.
local src = assert(arg[1], "usage: lua5.1 tools/build_seed.lua <ForeverArtisan_Contacts.lua>")
dofile(src)
local db = assert(ForeverArtisanContactsDB, "no ForeverArtisanContactsDB in " .. src)

local PROFS = { "Alchemy", "Blacksmithing", "Cooking", "Enchanting", "Engineering", "First Aid", "Fishing",
  "Herbalism", "Leatherworking", "Mining", "Skinning", "Tailoring" }
-- faction by town (an NPC's reaction value isn't reliable). Zephras Isle is the shared starting
-- island for both factions (Kerry, Oct 10).
local BOTH = { ["Booty Bay"] = true, ["Ratchet"] = true, ["Gadgetzan"] = true, ["Everlook"] = true, ["Zephras Isle"] = true }
local HORDE = { ["Orgrimmar"] = true, ["Undercity"] = true, ["Tirisfal Glades"] = true, ["Mulgore"] = true,
  ["Thunder Bluff"] = true, ["Durotar"] = true, ["The Barrens"] = true, ["Shadowprey Village"] = true,
  ["Grom'gol Base Camp"] = true, ["Silverpine Forest"] = true }
local ALLIANCE = { ["Stormwind City"] = true, ["Ironforge"] = true, ["Darnassus"] = true, ["Elwynn Forest"] = true,
  ["Dun Morogh"] = true, ["Teldrassil"] = true, ["Theramore Isle"] = true }

local function faction(e)
  for _, place in ipairs({ e.subzone, e.zone }) do
    if place and BOTH[place] then return "Both" end
  end
  for _, place in ipairs({ e.subzone, e.zone }) do
    if place and HORDE[place] then return "Horde" end
    if place and ALLIANCE[place] then return "Alliance" end
  end
  return nil -- unknown town: left out until someone adds it above
end

local function profOf(e)
  for _, sk in ipairs(e.skills or {}) do
    for _, p in ipairs(PROFS) do
      if (sk.skillReq and sk.skillReq:find("^" .. p)) or (sk.name and sk.name:find(p, 1, true)) then return p end
    end
  end
end

local function q(s) return string.format("%q", s) end
local function day(t) return t and (t - t % 86400 + 43200) or nil end -- noon UTC of that day

local list, skipped = {}, {}
for _, e in pairs(db.entries or {}) do
  if e.kind == "trainer" and e.npcId and e.name then
    local p, f = profOf(e), faction(e)
    if p and f then
      list[#list + 1] = { e = e, p = p, f = f }
    elseif p then
      skipped[#skipped + 1] = e.name .. " (" .. tostring(e.subzone or e.zone) .. ": unknown faction)"
    end
  end
end
table.sort(list, function(a, b) return a.e.npcId < b.e.npcId end)

local out = {}
local function w(s) out[#out + 1] = s end
w("-- GENERATED by tools/build_seed.lua from Trade Contacts data. Do not edit; rerun the script.")
w("-- Profession trainers met on the Forever beta. Trade Contacts shows them, marked \"seen on the")
w("-- Forever beta\", until you talk to them yourself (then your own record replaces the seed).")
w("local _, ns = ...")
w("ns.SEED_TRAINERS = {")
for _, it in ipairs(list) do
  local e = it.e
  w(("  { id = %d, n = %s, t = %s, prof = %s, f = %s, z = %s, s = %s, m = %s, x = %s, y = %s, seen = %s, skills = {")
    :format(e.npcId, q(e.name), e.title and q(e.title) or "nil", q(it.p), q(it.f), e.zone and q(e.zone) or "nil",
      e.subzone and q(e.subzone) or "nil", tostring(e.mapID or "nil"), tostring(e.x or "nil"), tostring(e.y or "nil"),
      tostring(day(e.lastSeen or e.seenAt) or "nil")))
  local skills = {}
  for _, sk in ipairs(e.skills or {}) do if sk.name then skills[#skills + 1] = sk end end
  table.sort(skills, function(a, b) return a.name < b.name end)
  for _, sk in ipairs(skills) do
    w(("    { n = %s, sk = %s, p = %s, lv = %s },"):format(q(sk.name), sk.skillReq and q(sk.skillReq) or "nil",
      tostring(sk.priceCopper or "nil"), tostring(sk.levelReq or "nil")))
  end
  w("  } },")
end
w("}")
print(table.concat(out, "\n"))
io.stderr:write(("%d profession trainers written.\n"):format(#list))
for _, s in ipairs(skipped) do io.stderr:write("skipped " .. s .. "\n") end
